apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080  
    - protocol: TCP
      name: admin
      port: 9990
      targetPort: 9990
  