apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  labels:
    app: metrics
spec:
  selector:
    app: metrics
  
  ports:
    - protocol: TCP
      name: http
      port: 8070
      targetPort: 8070
   