apiVersion: v1
kind: Service
metadata:
  name: credential-schema-service
  labels:
    app: credential-schema
spec:
  selector:
    app: credential-schema
  ports:
    - port: 3333
      targetPort: 3333
  type: ClusterIP
