apiVersion: v1
kind: Service
metadata:
  name: public-key-service
  labels:
    app: public-key
spec:
  selector:
    app: public-key
  ports:
  - name: http
    port: 3300
    targetPort: 3300
  type: ClusterIP
