apiVersion: v1
kind: Service
metadata:
  name: encryption-service
  labels:
    app: encryption
spec:

  selector:
    app: encryption
  ports:
    - protocol: TCP
      port: 8013
      targetPort: 8013
  