apiVersion: v1
kind: Service
metadata:
  name: digilocker-certificate-api-service
  labels:
    app: digilocker-certificate-api
spec:
  selector:
    app: digilocker-certificate-api
  ports:
  - name: http
    port: 8087
    targetPort: 8087
  type: ClusterIP
