apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  labels:
    app: registry
type: Opaque
stringData:
  connectionInfo_password: REPLACE_ME_CONNECTIONINFO_PASSWORD
  elastic_search_password: REPLACE_ME_ELASTIC_SEARCH_PASSWORD
  sunbird_sso_admin_client_secret: REPLACE_ME_SSO_ADMIN_CLIENT_SECRET
  filestorage_access_key: REPLACE_ME_FILESTORAGE_ACCESS_KEY
  filestorage_secret_key: REPLACE_ME_FILESTORAGE_SECRET_KEY
  sunbird_keycloak_user_password: REPLACE_ME_KEYCLOAK_USER_PASSWORD
