apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: registry 
spec:
  selector:
    app: registry
  
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081  
  type: LoadBalancer