apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  labels:
    app: elastic-search
type: Opaque
stringData:
  ELASTIC_PASSWORD: REPLACE_ME_ELASTIC_PASSWORD
  BASIC_AUTH: REPLACE_ME_BASIC_AUTH
