apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  
  ports:
    - protocol: TCP
      name: http
      port: 9092
      targetPort: 9092
   