apiVersion: v1
kind: Service
metadata:
  name: credential-service
  labels:
    app: credential
spec:
  selector:
    app: credential
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
