apiVersion: v1
kind: Secret
metadata:
  name: digilocker-certificate-api-secret
  labels:
    app: digilocker-certificate-api
type: Opaque
stringData:
  KEYCLOAK_CLIENT_SECRET: REPLACE_ME_KEYCLOAK_CLIENT_SECRET
  DIGILOCKER_HMAC_AUTHKEY: REPLACE_ME_DIGILOCKER_HMAC_AUTHKEY
