apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  labels:
    app: clickhouse
spec:

  selector:
    app: clickhouse
  ports:
    - protocol: TCP
      name: native
      port: 9002 #what other services will use to connect to clickhouse
      targetPort: 9000 #clickhouse native client port
    - protocol: TCP
      name: http
      port: 8123
      targetPort: 8123
  type: ClusterIP