apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  labels:
    app: minio
type: Opaque
stringData:
  MINIO_ROOT_USER: REPLACE_ME_MINIO_ROOT_USER
  MINIO_ROOT_PASSWORD: REPLACE_ME_MINIO_ROOT_PASSWORD
