apiVersion: v1
kind: Secret
metadata:
  name: claim-ms-secret
  labels:
    app: claim-ms
type: Opaque
stringData:
  connectionInfo_username: REPLACE_ME_CONNECTIONINFO_USERNAME
  connectionInfo_password: REPLACE_ME_CONNECTIONINFO_PASSWORD
