apiVersion: v1
kind: Service
metadata:
  name: notification-ms-service
  labels:
    app: notification-ms
spec:
  selector:
    app: notification-ms
  ports:
  - name: http
    port: 8765
    targetPort: 8765
  type: ClusterIP
