apiVersion: v1
kind: Service
metadata:
  name: claim-ms-service
  labels:
    app: claim-ms
spec:
  selector:
    app: claim-ms
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  type: ClusterIP
