apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  labels:
    app: keycloak
type: Opaque
stringData:
  DB_USER: REPLACE_ME_DB_USER
  DB_PASSWORD: REPLACE_ME_DB_PASSWORD
  KEYCLOAK_USER: REPLACE_ME_KEYCLOAK_USER
  KEYCLOAK_PASSWORD: REPLACE_ME_KEYCLOAK_PASSWORD
